# Generated by Django 6.0.2 on 2026-02-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organize',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='organization',
        ),
    ]
